### PR TITLE
fix searching issues

### PR DESCRIPTION
**Pull request by AipioxTechson**
## feat/fix search issues

Fixes: #25 

- [x] Has the code been formatted?
- [ ] Have dependencies/packages been added/removed?
      If so, please list them.

### Changes

Fixes the searching mechanism:
Frontend changes:
Doesn't pass the isCommunity prop for the all section
Uses images on all categories, and not solely All
Search functionality works

Backend:
changed search from description to name
can now chain requests when searching by text

### CODE REVIEW

**Review by jcserv — COMMENTED** [review]
Looks good, I noticed one inconsistent behaviour with course chats but I can't upload the file so check Discord!

**Review by Yousef-Bulbulia — CHANGES_REQUESTED** [review]
Hey Ritvik! Just a few things:
* The issue mentions that pressing the Enter key should initiate a search, but right now the only way to search is to click the Search button
* I don't think this was mentioned in the issue, but I just realized it now—if you search for something, the only way to get back to the homepage with all the chats is to search using an empty string! I feel like there should be an obvious, easy way to display all the groupchats again. Personally I think that clicking the "All" button at the top should do it. Also, I'd like to know how you feel about this, but I feel like pressing the back button on the webpage should undo the search and bring you back to where you were before searching.

**Review by jcserv — CHANGES_REQUESTED** [review]
Still running into the issue where the course feed is limited

Capture

**Review by jcserv — APPROVED** [review]

**Review by Yousef-Bulbulia — CHANGES_REQUESTED** [review]
The Enter key works perfectly, and so does the back button! The only thing is that right now some of the searches are returning unexpected results. For example, searching for "White Van" doesn't return the UTM White Van chat, and if you search for any of the CS courses like "csc108", "csc1085", or "GGRA01", their chats aren't returned.

**Review by Yousef-Bulbulia — APPROVED** [review]

**Pull request merged**
