### PR TITLE
change search functionality

### PR DESCRIPTION
**Pull request by NandoMancini**
## feat/search-mods

Fixes: #63 

- [X] Has the code been formatted?
- [ ] Have dependencies/packages been added/removed?
      

### Changes
List out all the changes, and then explain the changes made at a higher level

Change search functionaliy so that searches are made in all tab

### CODE REVIEW

**Review by Yousef-Bulbulia — CHANGES_REQUESTED** [review]
Hey Nando! I tried searching for groupchats, but it seems that the search bar and tabs still work the same way. For example, when I search for "SOC", I get matching course and community chats when I'm on the All tab, matching course chats on the Courses tab, and matching community chats on the Communities tab.

Basically, we want to change it so that the tabs don't act as filters for the search bar anymore, and instead will display every chat that falls under their respective category. Basically:
- If you click the All tab, all the chats will display
- If you click the Courses tab, all the course chats will display
- If you click the Communities tab, all the community chats will display
- If you search for a chat, only the matching chats will display, whether they're course chats or community chats

**Comment by AipioxTechson** [comment]
Looking more into this, I've noticed that this behaviour may be do to the fact that the url queries are coupled with the tabs. Since we search without respect to the community, the tab is set to all automatically.

**Comment by AipioxTechson** [comment]
Would it be a better idea to empty the search query when switching tabs, rather than removing the ability to search on a specific filter? that way, it isn't restrictive but also provides the most information with the least amount of clicks

**Comment by NandoMancini** [comment]
Weird, I did go over the feature with Jerry and we tried it out and got
what you were looking for. I will re test it and see what is going on

**Comment by NandoMancini** [comment]
I have been trying to recreate the problem, but if I try to search for CSC108 in the communities tab, it will give me results in the all tab, same way if I search for MCSS or WV while in the courses tab. Is this what you wanted or did I misunderstand the prompt?

**Comment by Yousef-Bulbulia** [comment]
Ah, I see! Yeah, I think that's a bit different than the intended functionality. However, after reading Aipiox's comments, maybe we should discuss what we want to do a bit more before moving on.

**Comment by Yousef-Bulbulia** [comment]
> Would it be a better idea to empty the search query when switching tabs, rather than removing the ability to search on a specific filter? that way, it isn't restrictive but also provides the most information with the least amount of clicks


Hmm, if we were to do that then we would keep filtering by tabs, but also reset the query when changing tabs, right? The thing is, if someone were to search up, say, "SOC" when they were in the Courses tab, and then switch over to the communities tab to find SOC related community chats, their search would be emptied after switching and they would have to search for "SOC" again. I feel like having to search again when switching tabs because your search query was emptied might be tedious for users.

Personally, I feel like it would be best if we separated the search bar from the tabs entirely. How would you guys feel about making it so that, when you search, whatever tab you're on gets deselected? That way, when you search, you're not on any tab, and as a result, no filtering happens. Everything that matches your search simply gets returned. And then if you want to see all the chats, all the course chats, or all the community chats, you can just click on one of the tabs.

**Comment by AipioxTechson** [comment]
I am fine with that, but we would need to hide the search bar when on a different tab!

**Comment by Yousef-Bulbulia** [comment]
Hmm I feel like if we were to do this we could leave the search bar where it is. The tabs could work to display all of their respective chats, and when someone wants to find a specific group of chats, they could just use the search bar. I imagine the only visual difference would be that when someone searches for chats and the results are returned, none of the tabs will be highlighted as selected.

**Pull request merged**
